name = "undercover-backend"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "RoomDO" }]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
